title: This is my awesome title
author: jdesbois
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome description of this throw away project

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
